version: '3'
services:
  server:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.server
    volumes:
      - type: bind
        source: ../
        target: /workspaces
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
#      - node_modules:/workspaces/Takehara-project/node_modules
    ports:
      - '3000:3000'
#    depends_on:
#      - application
#   application:
#     build:
#       context: ..
#       dockerfile: .devcontainer/Dockerfile.application
#     volumes:
#       - type: bind
#         source: ../
#         target: /workspaces
#       - node_modules:/workspaces/node_modules
#     ports:
#       - '8080:3000'
# volumes:
#   node_modules: